# Site settings
title: Just Another Blog
name: Dong Jiang
email: jd249326109@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  just mark something down.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jdflyfly.github.io" # the base hostname & protocol for your site
twitter_username: jd46027040
github_username:  jdflyfly

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  syntax_highlighter: rouge

#markdown: redcarpet
#redcarpet:
#  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]